### ISSUE TITLE
Mojibake on quote carousel

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#1]
The quotes shown on the quote carousel on the top page are preceded by an invalid character:
![screen shot 2017-04-05 at 16 19 24](https://cloud.githubusercontent.com/assets/2172537/24694125/ab95102c-1a1b-11e7-9ff0-7dfa8ee77a97.png)

The character is U+F10D, prepended by a `:before content` CSS rule [here](https://github.com/omegat-org/omegat-website/blob/5ba0b02a07e844d02a39c68f8daefc460a272bce/_sass/quote-carousel.sass#L44). However this is a private-use character and should not be used.

It's hard to suggest a replacement without knowing what the intention was, but perhaps something like ❝ (U+275D HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT)?

**Comment by briacp** [comment]
Right, the U+F10D was from the "Awesomefont" used in the css. I replaced it with U+275D from a standard font, it should solve the problem cross-platform.

**Comment by amake** [comment]
Sorry, I didn't realize that was supposed to be handled by a web font. I wouldn't mind using the web font as long as it loaded correctly. I usually browse with uBlock Origin enabled, which could have been the problem.
