### ISSUE TITLE
Nightly builds have moved to SourceForge

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#12]
Nightly builds have moved to SourceForge. [This commit](https://github.com/omegat-org/omegat-website/commit/6a947a59fe08c04fb044a94219ba0b1885fd3147) has the correct URL, but it appears that the site hasn't actually been updated yet.

Further, the ⓘ popup on the [download page](https://omegat.org/download) for Nightly Builds should be updated to remove any mention of CloudBees or DEV@Cloud.

**Comment by briacp** [comment]
The website should use the correct URL now. I also updated the popup text.
