### ISSUE TITLE
4.3.0 standard released

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#15]
I'm registering an issue so I can know when the site is updated, at which time I will push the master data for the in-app version check.

(The version check sends people to the website, so until the site is updated there is no sense in triggering the version check.)

**Comment by briacp** [comment]
The website is now   updated with 4.3.0 as the standard version. (https://github.com/omegat-org/omegat-website/commit/16b7ecb31f5e8b10fd11421d511591297f076a2b)

**Comment by brandelune** [comment]
Excellent ! Thank you Briac !
