### ISSUE TITLE
Mac dist is now "_Notarized"

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#18]
With 4.3.1 and 5.1.0 the recommended Mac distribution is now the "_Notarized" one, e.g. `OmegaT_5.1.0_Beta_Mac_Notarized.zip`. Sorry to keep changing this up, but it's important for the build system to be able to distinguish between merely "signed" and "signed and with a stapled notarization".

**Comment by briacp** [comment]
Thanks, it's fixed in https://github.com/omegat-org/omegat-website/commit/50d3f370e1ba0f00edc7a9884f1a752a3936586f all the `Mac_Signed` downloads are now `Mac_Notarized`.
