### ISSUE TITLE
Update support info

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#19]
I have [announced](https://groups.yahoo.com/neo/groups/OmegaT/conversations/messages/44763) that the user group is moving to SourceForge. The info on https://omegat.org/contact should be updated.

I am going to update links in the main repo as well, but the change is quite large since we include it in the source header:

```
/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 20xy John Doe
               Home page: http://www.omegat.org/
               Support center: http://groups.yahoo.com/group/OmegaT/

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/
```

Rather than chase the user group wherever it goes, I think we should have a `https://omegat.org/support` URL. While we could have that redirect to the mailing list directly, the SourceForge ML web interface is not very welcoming. So instead it could redirect to e.g. `https://omegat.org/contact`.

While we're on the subject, I felt like the website topology could be improved:

- I was looking for "Support" but couldn't find it. In the header I looked under "Resources" but that wasn't right. Maybe a "Support" link in the header could be added, linking to https://omegat.org/contact?
- I eventually found "Contact and Support" in the footer. I feel like lumping "Contact" together with "Support" seemed unintuitive, but I don't have a suggestion that would make a big improvement. Maybe "Community" or "Community Support"?
- I feel like what most people probably want is the "support" part, not "contact". Maybe rename https://omegat.org/contact to https://omegat.org/support (https://omegat.org/contact can redirect) and even keep the content the same?

**Comment by briacp** [comment]
Fixed in adfe68f4bffee0c344c65b40aadd7f688af3ac93 and 6c2517c6ccc3be608151dbc58ca7fa15de5da80b.
The links to the support/contact page should be more prominent.
