### ISSUE TITLE
Please get an SSL cert for http://www.omegat.org/

### ISSUE THREAD

**Issue by hexagonrecursion** [omegat-org/omegat-website#34]
Your main website at https://omegat.org/ is protected by SSL, but some sources (eg [this list](https://opensource.com/article/17/6/open-source-localization-tools) ) link to http://www.omegat.org/ instead. Could you please protect that too?

**Comment by briacp** [comment]
Even though the opensource.com article links to the http version (we can't do anything about it), we always redirect on the https version of the website hosted on Github.
Moreover, there's no way to use SSL for an http address (that's what https is for).
