### ISSUE TITLE
Confirm domain ownership for Sonatype OSSRH

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#36]
I am working on migrating our dependency binaries off of Bintray/JCenter, which is shutting down in May.

I am moving them to Sonatype OSSRH, which syncs to Maven Central.

Sonatype requires me to confirm ownership of the omegat.org domain so that we can claim the `org.omegat` Maven group.

Could you please add a TXT record to the omegat.org domain with content `OSSRH-67500`?

Details: https://issues.sonatype.org/browse/OSSRH-67500

**Comment by amake** [comment]
Also for reference here is the ticket from when I set up an account for my personal projects: https://issues.sonatype.org/browse/OSSRH-67327

**Comment by briacp** [comment]
The DNS entry has been added
`omegat.org.		3600	TXT	"OSSRH-67500"`

**Comment by amake** [comment]
Thank you!
