### ISSUE TITLE
SourceForge web is now HTTPS

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#4]
The canonical SourceForge web URLs have changed from

http://omegat.sourceforge.net/

to

https://omegat.sourceforge.io/

There are redirects from the old to the new, so (probably) nothing is currently broken, but it would be nice to update things.

**Comment by amake** [comment]
We initially reversed this change but are now finally moving forward with it.

**Comment by briacp** [comment]
All URLs are now pointing to https://omegat.sourceforge.io/
