### ISSUE TITLE
Web Start page on SourceForge web

### ISSUE THREAD

**Issue by amake** [omegat-org/omegat-website#5]
There is a page specifically about the Java Web Start distribution of OmegaT here:

https://omegat.sourceforge.io/webstart.html

This seems redundant to me; if all the information on that page is available on omegat.org then we could get rid of it.

**Comment by briacp** [comment]
I don't have the permission to overwrite this file on the sourceforge SFTP. You can replace the webstart.html file with this one, it will make a redirection to the current Download page.

[webstart.zip](https://github.com/omegat-org/omegat-website/files/1499249/webstart.zip)

**Comment by amake** [comment]
Thanks, I've replaced it with your redirect.
