### ISSUE TITLE
Refreshing Corsican pages on OmegaT Website

### ISSUE THREAD

**Issue by Patriccollu** [omegat-org/omegat-website#83]
Hello,

I noticed new pages [Install](https://omegat.org/co/install) and [Policies](https://omegat.org/co/policies) on OmegaT Website as well as other recent changes, such as [Contributing link](https://omegat.org/co/documentation#developers). Unfortunately, If **Corsican** language is selected, the text is still in English!

I checked on OmegaT localization Website and confirm the [Corsican translation](https://github.com/OmegaT-L10N/co) is ready for these pages.

Do I need to do something in order to see **Corsican** Webpages updated?

Best regards,
Patriccollu.

**Comment by brandelune** [comment]
Can you confirm that you used the latest l10n project? I'm not seeing the corresponding items in:

https://github.com/OmegaT-L10N/co/blob/master/target/website/yml/co.yml

Also the pages "install.html" and "policies.html" are not available from your target folder. Can you please update your target folder?

**Comment by Patriccollu** [comment]
Hello @brandelune ,

Yes, I'm using the latest l10n project, as Kos requested some time ago.
But I didn't know that it was necessary to "commit the target files"!
So far, I was just informing Kos before each new release about what had been changed.

I just committed the target files and the pages "install.html" and "policies.html" are now available.
https://github.com/OmegaT-L10N/co/blob/master/target/website/yml/co.yml
Please can you check and confirm it's okay now.

Best regards,
Patriccollu.

**Comment by briacp** [comment]
The website has been updated with your latest updates.

Grazie Patriccollu
